[project]
name = "reinforcement-learning-squash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gym>=0.26.2",
    "numpy>=2.1.3",
    "pygame>=2.6.1",
    "tensorflow>=2.19.0",
    "termcolor>=3.0.0",
]
